### ISSUE TITLE
qFlipper SIGSEGV

### ISSUE THREAD

**Issue by ZeroChaos-** [flipperdevices/qFlipper#59]
First and foremost, thank you for your interest in making qFlipper better by reporting bugs!

**Describe the bug**
What were you trying to do?
Run qFlipper

**To Reproduce**
Build git HEAD on Gentoo following build instructions.

**Expected behavior**
The UI to appear

**Actual behavior**
Crashes with SIGSEGV

**Additional troubleshooting**
1. Does the issue persist if you try multiple times?
Persistent across rebuilds

**Additional context**
```
Starting program: /usr/bin/qFlipper 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff2f56640 (LWP 24891)]
[New Thread 0x7ffff1600640 (LWP 24892)]
[New Thread 0x7ffff0dff640 (LWP 24893)]
[New Thread 0x7fffe3fff640 (LWP 24894)]
[New Thread 0x7fffe37fe640 (LWP 24895)]
[New Thread 0x7fffe2ffd640 (LWP 24897)]
[Thread 0x7fffe2ffd640 (LWP 24897) exited]
[New Thread 0x7fffe2ffd640 (LWP 24898)]
[New Thread 0x7fffe2437640 (LWP 24899)]
[Thread 0x7fffe2ffd640 (LWP 24898) exited]
[New Thread 0x7fffe2ffd640 (LWP 24900)]
[New Thread 0x7fffe1c36640 (LWP 24901)]
[Thread 0x7fffe2437640 (LWP 24899) exited]
[Thread 0x7fffe2ffd640 (LWP 24900) exited]
[Thread 0x7fffe1c36640 (LWP 24901) exited]
[New Thread 0x7fffe1c36640 (LWP 24902)]
[New Thread 0x7fffe2ffd640 (LWP 24904)]
[Thread 0x7fffe1c36640 (LWP 24902) exited]
[Thread 0x7fffe2ffd640 (LWP 24904) exited]
[New Thread 0x7fffe2ffd640 (LWP 24905)]
[New Thread 0x7fffe1c36640 (LWP 24906)]
[New Thread 0x7fffe2437640 (LWP 24907)]
[New Thread 0x7fffe1435640 (LWP 24908)]
[New Thread 0x7fffe0c34640 (LWP 24909)]
[New Thread 0x7fffcbfff640 (LWP 24910)]
[New Thread 0x7fffcb7fe640 (LWP 24911)]
[New Thread 0x7fffca8ab640 (LWP 24912)]
[New Thread 0x7fffca0aa640 (LWP 24913)]
[New Thread 0x7fffc98a9640 (LWP 24914)]
[New Thread 0x7fffc90a8640 (LWP 24915)]

Thread 20 "QQmlThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcb7fe640 (LWP 24911)]
0x00007ffff6fb0ab0 in ?? () from /usr/lib64/libQt5Qml.so.5
(gdb) bt
#0  0x00007ffff6fb0ab0 in  () at /usr/lib64/libQt5Qml.so.5
#1  0x00007ffff6fb0e36 in  () at /usr/lib64/libQt5Qml.so.5
#2  0x00007ffff6faee9f in  () at /usr/lib64/libQt5Qml.so.5
#3  0x00007ffff6faf2df in  () at /usr/lib64/libQt5Qml.so.5
#4  0x00007ffff6faf5e7 in  () at /usr/lib64/libQt5Qml.so.5
#5  0x00007ffff6f42a2f in  () at /usr/lib64/libQt5Qml.so.5
#6  0x00007ffff6f46a86 in  () at /usr/lib64/libQt5Qml.so.5
#7  0x00007ffff6f3bcf5 in QQmlDataBlob::tryDone() () at /usr/lib64/libQt5Qml.so.5
#8  0x00007ffff6f77337 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib64/libQt5Qml.so.5
#9  0x00007ffff6f7ad7f in void QQmlTypeLoader::doLoad<CachedLoader>(CachedLoader const&, QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#10 0x00007ffff6f77388 in QQmlTypeLoader::loadWithCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#11 0x00007ffff6f7925d in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#12 0x00007ffff6f45810 in  () at /usr/lib64/libQt5Qml.so.5
#13 0x00007ffff6f476db in  () at /usr/lib64/libQt5Qml.so.5
#14 0x00007ffff6f77310 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib64/libQt5Qml.so.5
#15 0x00007ffff6f7ad7f in void QQmlTypeLoader::doLoad<CachedLoader>(CachedLoader const&, QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#16 0x00007ffff6f77388 in QQmlTypeLoader::loadWithCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#17 0x00007ffff6f7925d in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#18 0x00007ffff6f45810 in  () at /usr/lib64/libQt5Qml.so.5
#19 0x00007ffff6f476db in  () at /usr/lib64/libQt5Qml.so.5
#20 0x00007ffff6f77310 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib64/libQt5Qml.so.5
#21 0x00007ffff6f7ad7f in void QQmlTypeLoader::doLoad<CachedLoader>(CachedLoader const&, QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#22 0x00007ffff6f77388 in QQmlTypeLoader::loadWithCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#23 0x00007ffff6f7925d in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#24 0x00007ffff6f45810 in  () at /usr/lib64/libQt5Qml.so.5
#25 0x00007ffff6f476db in  () at /usr/lib64/libQt5Qml.so.5
#26 0x00007ffff6f77310 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib64/libQt5Qml.so.5
#27 0x00007ffff6f4ce9f in  () at /usr/lib64/libQt5Qml.so.5
#28 0x00007ffff6fc2edb in  () at /usr/lib64/libQt5Qml.so.5
#29 0x00007ffff6fc3106 in  () at /usr/lib64/libQt5Qml.so.5
#30 0x00007ffff76c2bf1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#31 0x00007ffff69cc000 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#32 0x00007ffff69cc94d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib64/libQt5Core.so.5
#33 0x00007ffff6a01df3 in  () at /usr/lib64/libQt5Core.so.5
#34 0x00007ffff5737d37 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#35 0x00007ffff5737f9a in  () at /usr/lib64/libglib-2.0.so.0
#36 0x00007ffff573804c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#37 0x00007ffff6a019a8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#38 0x00007ffff69c971e in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#39 0x00007ffff68a2afe in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#40 0x00007ffff6fc29cf in  () at /usr/lib64/libQt5Qml.so.5
#41 0x00007ffff68a3b09 in  () at /usr/lib64/libQt5Core.so.5
#42 0x00007ffff638f157 in  () at /lib64/libc.so.6
#43 0x00007ffff6411bbc in  () at /lib64/libc.so.6
(gdb) info threads
  Id   Target Id                                           Frame 
  1    Thread 0x7ffff37457c0 (LWP 24887) "qFlipper"        0x00007ffff638be9a in ?? () from /lib64/libc.so.6
  2    Thread 0x7ffff2f56640 (LWP 24891) "QXcbEventQueue"  0x00007ffff640517f in poll () from /lib64/libc.so.6
  3    Thread 0x7ffff1600640 (LWP 24892) "gmain"           0x00007ffff640517f in poll () from /lib64/libc.so.6
  4    Thread 0x7ffff0dff640 (LWP 24893) "gdbus"           0x00007ffff640517f in poll () from /lib64/libc.so.6
  5    Thread 0x7fffe3fff640 (LWP 24894) "dconf worker"    0x00007ffff640517f in poll () from /lib64/libc.so.6
  6    Thread 0x7fffe37fe640 (LWP 24895) "pool-qFlipper"   0x00007ffff640a539 in syscall () from /lib64/libc.so.6
  14   Thread 0x7fffe2ffd640 (LWP 24905) "pool-qFlipper"   0x00007ffff640a539 in syscall () from /lib64/libc.so.6
  15   Thread 0x7fffe1c36640 (LWP 24906) "libusb_event"    0x00007ffff640517f in poll () from /lib64/libc.so.6
  16   Thread 0x7fffe2437640 (LWP 24907) "Qt bearer threa" 0x00007ffff640517f in poll () from /lib64/libc.so.6
  17   Thread 0x7fffe1435640 (LWP 24908) "QDBusConnection" 0x00007ffff640517f in poll () from /lib64/libc.so.6
  18   Thread 0x7fffe0c34640 (LWP 24909) "QNetworkAccessM" 0x00007ffff640a539 in syscall () from /lib64/libc.so.6
  19   Thread 0x7fffcbfff640 (LWP 24910) "Thread (pooled)" 0x00007ffff638be9a in ?? () from /lib64/libc.so.6
* 20   Thread 0x7fffcb7fe640 (LWP 24911) "QQmlThread"      0x00007ffff6fb0ab0 in ?? () from /usr/lib64/libQt5Qml.so.5
  21   Thread 0x7fffca8ab640 (LWP 24912) "Thread (pooled)" 0x00007ffff638be9a in ?? () from /lib64/libc.so.6
  22   Thread 0x7fffca0aa640 (LWP 24913) "Thread (pooled)" 0x00007ffff638be9a in ?? () from /lib64/libc.so.6
  23   Thread 0x7fffc98a9640 (LWP 24914) "Thread (pooled)" 0x00007ffff638be9a in ?? () from /lib64/libc.so.6
  24   Thread 0x7fffc90a8640 (LWP 24915) "Thread (pooled)" 0x00007ffff638be9a in ?? () from /lib64/libc.so.6
(gdb) thread apply all bt full

Thread 24 (Thread 0x7fffc90a8640 (LWP 24915) "Thread (pooled)"):
#0  0x00007ffff638be9a in  () at /lib64/libc.so.6
#1  0x00007ffff638e844 in pthread_cond_timedwait () at /lib64/libc.so.6
#2  0x00007ffff68a7fb0 in  () at /usr/lib64/libQt5Core.so.5
#3  0x00007ffff68a7d09 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff68a6187 in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff68a3b09 in  () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff638f157 in  () at /lib64/libc.so.6
#7  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 23 (Thread 0x7fffc98a9640 (LWP 24914) "Thread (pooled)"):
#0  0x00007ffff638be9a in  () at /lib64/libc.so.6
#1  0x00007ffff638e844 in pthread_cond_timedwait () at /lib64/libc.so.6
#2  0x00007ffff68a7fb0 in  () at /usr/lib64/libQt5Core.so.5
#3  0x00007ffff68a7d09 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff68a6187 in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff68a3b09 in  () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff638f157 in  () at /lib64/libc.so.6
#7  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 22 (Thread 0x7fffca0aa640 (LWP 24913) "Thread (pooled)"):
#0  0x00007ffff638be9a in  () at /lib64/libc.so.6
#1  0x00007ffff638e844 in pthread_cond_timedwait () at /lib64/libc.so.6
#2  0x00007ffff68a7fb0 in  () at /usr/lib64/libQt5Core.so.5
#3  0x00007ffff68a7d09 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff68a6187 in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff68a3b09 in  () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff638f157 in  () at /lib64/libc.so.6
#7  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 21 (Thread 0x7fffca8ab640 (LWP 24912) "Thread (pooled)"):
#0  0x00007ffff638be9a in  () at /lib64/libc.so.6
#1  0x00007ffff638e844 in pthread_cond_timedwait () at /lib64/libc.so.6
#2  0x00007ffff68a7fb0 in  () at /usr/lib64/libQt5Core.so.5
#3  0x00007ffff68a7d09 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff68a6187 in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff68a3b09 in  () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff638f157 in  () at /lib64/libc.so.6
#7  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 20 (Thread 0x7fffcb7fe640 (LWP 24911) "QQmlThread"):
#0  0x00007ffff6fb0ab0 in  () at /usr/lib64/libQt5Qml.so.5
#1  0x00007ffff6fb0e36 in  () at /usr/lib64/libQt5Qml.so.5
#2  0x00007ffff6faee9f in  () at /usr/lib64/libQt5Qml.so.5
--Type <RET> for more, q to quit, c to continue without paging--c
#3  0x00007ffff6faf2df in  () at /usr/lib64/libQt5Qml.so.5
#4  0x00007ffff6faf5e7 in  () at /usr/lib64/libQt5Qml.so.5
#5  0x00007ffff6f42a2f in  () at /usr/lib64/libQt5Qml.so.5
#6  0x00007ffff6f46a86 in  () at /usr/lib64/libQt5Qml.so.5
#7  0x00007ffff6f3bcf5 in QQmlDataBlob::tryDone() () at /usr/lib64/libQt5Qml.so.5
#8  0x00007ffff6f77337 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib64/libQt5Qml.so.5
#9  0x00007ffff6f7ad7f in void QQmlTypeLoader::doLoad<CachedLoader>(CachedLoader const&, QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#10 0x00007ffff6f77388 in QQmlTypeLoader::loadWithCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#11 0x00007ffff6f7925d in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#12 0x00007ffff6f45810 in  () at /usr/lib64/libQt5Qml.so.5
#13 0x00007ffff6f476db in  () at /usr/lib64/libQt5Qml.so.5
#14 0x00007ffff6f77310 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib64/libQt5Qml.so.5
#15 0x00007ffff6f7ad7f in void QQmlTypeLoader::doLoad<CachedLoader>(CachedLoader const&, QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#16 0x00007ffff6f77388 in QQmlTypeLoader::loadWithCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#17 0x00007ffff6f7925d in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#18 0x00007ffff6f45810 in  () at /usr/lib64/libQt5Qml.so.5
#19 0x00007ffff6f476db in  () at /usr/lib64/libQt5Qml.so.5
#20 0x00007ffff6f77310 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib64/libQt5Qml.so.5
#21 0x00007ffff6f7ad7f in void QQmlTypeLoader::doLoad<CachedLoader>(CachedLoader const&, QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#22 0x00007ffff6f77388 in QQmlTypeLoader::loadWithCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#23 0x00007ffff6f7925d in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#24 0x00007ffff6f45810 in  () at /usr/lib64/libQt5Qml.so.5
#25 0x00007ffff6f476db in  () at /usr/lib64/libQt5Qml.so.5
#26 0x00007ffff6f77310 in QQmlTypeLoader::setCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*) () at /usr/lib64/libQt5Qml.so.5
#27 0x00007ffff6f4ce9f in  () at /usr/lib64/libQt5Qml.so.5
#28 0x00007ffff6fc2edb in  () at /usr/lib64/libQt5Qml.so.5
#29 0x00007ffff6fc3106 in  () at /usr/lib64/libQt5Qml.so.5
#30 0x00007ffff76c2bf1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#31 0x00007ffff69cc000 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#32 0x00007ffff69cc94d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib64/libQt5Core.so.5
#33 0x00007ffff6a01df3 in  () at /usr/lib64/libQt5Core.so.5
#34 0x00007ffff5737d37 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#35 0x00007ffff5737f9a in  () at /usr/lib64/libglib-2.0.so.0
#36 0x00007ffff573804c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#37 0x00007ffff6a019a8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#38 0x00007ffff69c971e in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#39 0x00007ffff68a2afe in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#40 0x00007ffff6fc29cf in  () at /usr/lib64/libQt5Qml.so.5
#41 0x00007ffff68a3b09 in  () at /usr/lib64/libQt5Core.so.5
#42 0x00007ffff638f157 in  () at /lib64/libc.so.6
#43 0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 19 (Thread 0x7fffcbfff640 (LWP 24910) "Thread (pooled)"):
#0  0x00007ffff638be9a in  () at /lib64/libc.so.6
#1  0x00007ffff638e844 in pthread_cond_timedwait () at /lib64/libc.so.6
#2  0x00007ffff68a7fb0 in  () at /usr/lib64/libQt5Core.so.5
#3  0x00007ffff68a7d09 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff68a6187 in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff68a3b09 in  () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff638f157 in  () at /lib64/libc.so.6
#7  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 18 (Thread 0x7fffe0c34640 (LWP 24909) "QNetworkAccessM"):
#0  0x00007ffff640a539 in syscall () at /lib64/libc.so.6
#1  0x00007ffff68a52b0 in  () at /usr/lib64/libQt5Core.so.5
#2  0x00007ffff69ec04c in  () at /usr/lib64/libQt5Core.so.5
#3  0x00007ffff69ec0f4 in  () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff6ce464d in  () at /usr/lib64/libQt5Network.so.5
#5  0x00007ffff69ec0f4 in  () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff6d39519 in  () at /usr/lib64/libQt5Network.so.5
#7  0x00007ffff6d3cf94 in  () at /usr/lib64/libQt5Network.so.5
#8  0x00007ffff6d3d430 in  () at /usr/lib64/libQt5Network.so.5
#9  0x00007ffff69ec0f4 in  () at /usr/lib64/libQt5Core.so.5
#10 0x00007ffff6d11572 in  () at /usr/lib64/libQt5Network.so.5
#11 0x00007ffff6d11f45 in  () at /usr/lib64/libQt5Network.so.5
#12 0x00007ffff6d1fcc0 in  () at /usr/lib64/libQt5Network.so.5
#13 0x00007ffff76c2bf1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff69cc000 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#15 0x00007ffff6a0220e in  () at /usr/lib64/libQt5Core.so.5
#16 0x00007ffff5737d37 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#17 0x00007ffff5737f9a in  () at /usr/lib64/libglib-2.0.so.0
#18 0x00007ffff573804c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#19 0x00007ffff6a019a8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#20 0x00007ffff69c971e in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#21 0x00007ffff68a2afe in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#22 0x00007ffff68a3b09 in  () at /usr/lib64/libQt5Core.so.5
#23 0x00007ffff638f157 in  () at /lib64/libc.so.6
#24 0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 17 (Thread 0x7fffe1435640 (LWP 24908) "QDBusConnection"):
#0  0x00007ffff640517f in poll () at /lib64/libc.so.6
#1  0x00007ffff5737f42 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff573804c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff6a019a8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff69c971e in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff68a2afe in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff30f5f8b in  () at /usr/lib64/libQt5DBus.so.5
#7  0x00007ffff68a3b09 in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007ffff638f157 in  () at /lib64/libc.so.6
#9  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 16 (Thread 0x7fffe2437640 (LWP 24907) "Qt bearer threa"):
#0  0x00007ffff640517f in poll () at /lib64/libc.so.6
#1  0x00007ffff5737f42 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff573804c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff6a019a8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff69c971e in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff68a2afe in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff68a3b09 in  () at /usr/lib64/libQt5Core.so.5
#7  0x00007ffff638f157 in  () at /lib64/libc.so.6
#8  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 15 (Thread 0x7fffe1c36640 (LWP 24906) "libusb_event"):
#0  0x00007ffff640517f in poll () at /lib64/libc.so.6
#1  0x00007ffff7f72bbb in  () at /lib64/libusb-1.0.so.0
#2  0x00007ffff638f157 in  () at /lib64/libc.so.6
#3  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 14 (Thread 0x7fffe2ffd640 (LWP 24905) "pool-qFlipper"):
#0  0x00007ffff640a539 in syscall () at /lib64/libc.so.6
#1  0x00007ffff5773828 in g_cond_wait_until () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff571323b in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff5755c5a in  () at /usr/lib64/libglib-2.0.so.0
#4  0x00007ffff57555e7 in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff638f157 in  () at /lib64/libc.so.6
#6  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 6 (Thread 0x7fffe37fe640 (LWP 24895) "pool-qFlipper"):
#0  0x00007ffff640a539 in syscall () at /lib64/libc.so.6
#1  0x00007ffff5773828 in g_cond_wait_until () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff571323b in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff5755c5a in  () at /usr/lib64/libglib-2.0.so.0
#4  0x00007ffff57555e7 in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff638f157 in  () at /lib64/libc.so.6
#6  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 5 (Thread 0x7fffe3fff640 (LWP 24894) "dconf worker"):
#0  0x00007ffff640517f in poll () at /lib64/libc.so.6
#1  0x00007ffff5737f42 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff573804c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff05961c2 in  () at /usr/lib64/gio/modules/libdconfsettings.so
#4  0x00007ffff57555e7 in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff638f157 in  () at /lib64/libc.so.6
#6  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 4 (Thread 0x7ffff0dff640 (LWP 24893) "gdbus"):
#0  0x00007ffff640517f in poll () at /lib64/libc.so.6
#1  0x00007ffff5737f42 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff57382c3 in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff1a42239 in  () at /usr/lib64/libgio-2.0.so.0
#4  0x00007ffff57555e7 in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff638f157 in  () at /lib64/libc.so.6
#6  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 3 (Thread 0x7ffff1600640 (LWP 24892) "gmain"):
#0  0x00007ffff640517f in poll () at /lib64/libc.so.6
#1  0x00007ffff5737f42 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff573804c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff573807d in  () at /usr/lib64/libglib-2.0.so.0
#4  0x00007ffff57555e7 in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff638f157 in  () at /lib64/libc.so.6
#6  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 2 (Thread 0x7ffff2f56640 (LWP 24891) "QXcbEventQueue"):
#0  0x00007ffff640517f in poll () at /lib64/libc.so.6
#1  0x00007ffff3789c2c in  () at /usr/lib64/libxcb.so.1
#2  0x00007ffff378b307 in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
#3  0x00007ffff31a00cc in  () at /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007ffff68a3b09 in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff638f157 in  () at /lib64/libc.so.6
#6  0x00007ffff6411bbc in  () at /lib64/libc.so.6

Thread 1 (Thread 0x7ffff37457c0 (LWP 24887) "qFlipper"):
#0  0x00007ffff638be9a in  () at /lib64/libc.so.6
#1  0x00007ffff638e540 in pthread_cond_wait () at /lib64/libc.so.6
#2  0x00007ffff68a7fba in  () at /usr/lib64/libQt5Core.so.5
#3  0x00007ffff68a7d09 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff6fc2fd3 in  () at /usr/lib64/libQt5Qml.so.5
#5  0x00007ffff6f7add7 in void QQmlTypeLoader::doLoad<CachedLoader>(CachedLoader const&, QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#6  0x00007ffff6f77388 in QQmlTypeLoader::loadWithCachedUnit(QQmlDataBlob*, QV4::CompiledData::Unit const*, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#7  0x00007ffff6f7925d in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib64/libQt5Qml.so.5
#8  0x00007ffff6f61caa in QQmlComponentPrivate::loadUrl(QUrl const&, QQmlComponent::CompilationMode) () at /usr/lib64/libQt5Qml.so.5
#9  0x00007ffff6f9d556 in QQmlApplicationEnginePrivate::startLoad(QUrl const&, QByteArray const&, bool) () at /usr/lib64/libQt5Qml.so.5
#10 0x00007ffff6f9d64f in QQmlApplicationEngine::load(QUrl const&) () at /usr/lib64/libQt5Qml.so.5
#11 0x0000555555576e3b in  ()
#12 0x0000555555578d66 in  ()
#13 0x0000555555576206 in  ()
#14 0x00007ffff63302fc in  () at /lib64/libc.so.6
#15 0x00007ffff63303a8 in __libc_start_main () at /lib64/libc.so.6
#16 0x0000555555576301 in  ()
```

**Comment by gsurkov** [comment]
Could you please tell what exact version of Qt is installed on your system?
Does the pre-built AppImage version run on it?

**Comment by ZeroChaos-** [comment]
dev-qt/qtcore-5.15.3
Yes, the pre-built AppImage does work.

**Comment by zhovner** [comment]
@ZeroChaos- do you want to make an eBuild of qFlipper for Gentoo?
Otherwise, we should close this issue and recommend to use AppImage.

**Comment by ZeroChaos-** [comment]
That was my goal, yes

**Comment by NetBUG** [comment]
Same issue.
```netbug@netbug-mbp2 MacOS % qmake --version
QMake version 3.1
Using Qt version 6.3.1 in /opt/homebrew/lib

./qFlipper
zsh: killed     ./qFlipper

netbug@netbug-mbp2 MacOS % uname -a
Darwin netbug-mbp2.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64```

**Comment by blshkv** [comment]
hello all, 

the problem is with ```3rdparty``` directory and its nanopb (the only dependency so far).
Basically, that symlink is not getting included in a release tar-ball and that's a good thing. However, the compilation does not really fail when there is no nanopd found.

Currently, qmake scripts expects a bundled nanopb only. I patched it to search in the system libraries instead.
You might want to adopt the patch and make it more universal.
